# Generated by Django 2.1.3 on 2019-08-07 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('iban', models.CharField(max_length=40)),
                ('admin_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_debtors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Open'), ('1', 'Overdue'), ('2', 'Paid')], default='0', max_length=2)),
                ('amount', models.IntegerField()),
                ('due_date', models.DateField()),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.Debtor')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
