# Generated by Django 2.1.3 on 2019-08-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0003_auto_20190807_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
